//! Embed every verifying public key under `keys/` into `PUBLIC_KEY_RING`.
//!
//! Naming: `{product}.{kid}.public.key` (e.g. `super-pro.k_0ac64a3f.public.key`).
//! `kid` is `k_<8 hex chars>` derived from the Ed25519 public key (see `kid_for_public_bytes`).
//! These files are committed so OSS contributors can build offline.
//! Release CI upserts Manager keys via fetch-verifying-keys.sh.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

fn main() {
    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let keys_dir = manifest_dir.join("keys");
    println!("cargo:rerun-if-changed={}", keys_dir.display());

    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());
    let out_file = out_dir.join("public_key_ring.rs");

    let entries = collect_keys(&keys_dir);
    if entries.is_empty() {
        panic!(
            "no verifying keys in {} — need committed *.public.key \
             (maintainers: curate keys/ or Release CI fetch-verifying-keys)",
            keys_dir.display()
        );
    }

    let mut kids_seen = std::collections::BTreeSet::new();
    let mut ring_items = Vec::new();

    for (kid, path) in &entries {
        if !kids_seen.insert(kid.clone()) {
            panic!(
                "duplicate verifying kid '{kid}' under {}",
                keys_dir.display()
            );
        }
        let meta = fs::metadata(path).unwrap_or_else(|e| {
            panic!("stat {}: {e}", path.display());
        });
        if meta.len() != 32 {
            panic!(
                "{} is {} bytes (Ed25519 public key must be 32)",
                path.display(),
                meta.len()
            );
        }
        println!("cargo:rerun-if-changed={}", path.display());
        let path_lit = path_literal(path);
        ring_items.push(format!(
            "    EmbeddedPublicKey {{\n        kid: \"{}\",\n        bytes: include_bytes!({path_lit}),\n    }}",
            escape_str(kid)
        ));
    }

    let body = format!(
        "// @generated by common/build.rs — do not edit\n\
         /// Verifying keyring: every `keys/*.public.key` at compile time.\n\
         pub const PUBLIC_KEY_RING: &[EmbeddedPublicKey] = &[\n{}\n];\n",
        ring_items.join(",\n")
    );

    fs::write(&out_file, body).unwrap_or_else(|e| {
        panic!("write {}: {e}", out_file.display());
    });
}

fn collect_keys(keys_dir: &Path) -> Vec<(String, PathBuf)> {
    let Ok(rd) = fs::read_dir(keys_dir) else {
        return Vec::new();
    };
    let mut out = Vec::new();
    for entry in rd.flatten() {
        let path = entry.path();
        if !path.is_file() {
            continue;
        }
        let Some(name) = path.file_name().and_then(|n| n.to_str()) else {
            continue;
        };
        let Some(kid) = kid_from_filename(name) else {
            continue;
        };
        out.push((kid, path));
    }
    out.sort_by(|a, b| a.0.cmp(&b.0));
    out
}

fn kid_from_filename(name: &str) -> Option<String> {
    let stem = name.strip_suffix(".public.key")?;
    if stem.is_empty() || stem.contains('/') {
        return None;
    }
    // `{product}.{kid}` → kid; bare `{kid}` also allowed.
    let kid = match stem.split_once('.') {
        Some((_product, kid)) if !kid.is_empty() => kid,
        None => stem,
        Some((_, _)) => return None,
    };
    if !kid
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || c == '_' || c == '-')
    {
        return None;
    }
    Some(kid.to_string())
}

fn path_literal(path: &Path) -> String {
    let abs = fs::canonicalize(path).unwrap_or_else(|_| path.to_path_buf());
    format!("\"{}\"", escape_str(&abs.to_string_lossy()))
}

fn escape_str(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}
