use super::claims::{LicenseClaims, LicenseInfo};
use anyhow::Context;
use base64::{Engine as _, engine::general_purpose::STANDARD as BASE64};
use ed25519_dalek::{Signature, Verifier, VerifyingKey};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::time::{SystemTime, UNIX_EPOCH};

/// One verifying key shipped inside this superd build.
#[derive(Debug, Clone, Copy)]
pub struct EmbeddedPublicKey {
    pub kid: &'static str,
    pub bytes: &'static [u8],
}

// `PUBLIC_KEY_RING` — every `keys/{product}.{kid}.public.key` at compile time.
// Generated by build.rs; Release CI upserts via fetch-verifying-keys.sh.
include!(concat!(env!("OUT_DIR"), "/public_key_ring.rs"));

/// Derive stable signing key id from an Ed25519 public key (Manager + OSS convention).
pub fn kid_for_public_bytes(bytes: &[u8; 32]) -> String {
    let hex: String = bytes[..4].iter().map(|b| format!("{b:02x}")).collect();
    format!("k_{hex}")
}

/// Renewal / purchase page (Get Super Pro). Edition comparison: feature matrix.
pub const LICENSE_UPGRADE_URL: &str = "https://super.docs.sconts.com/go/pro/";

/// Free 90-day Pro trial during public beta (Portal claim).
pub const LICENSE_TRIAL_URL: &str =
    "https://platform.ddl.sconts.com/portal/claim?product=super-pro&plan=first-trials-001";

/// Short footer for CLI / log messages when license verification fails.
pub fn license_help_footer() -> String {
    format!("More: {LICENSE_UPGRADE_URL} — free Pro trial: {LICENSE_TRIAL_URL}")
}

/// One Ed25519 verifying key compiled into this binary (`PUBLIC_KEY_RING` entry).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EmbeddedVerifyingKeyInfo {
    pub kid: String,
    /// Short fingerprint for support (first 8 hex chars of the 32-byte public key).
    pub fingerprint: String,
}

fn verifying_key_fingerprint(bytes: &[u8]) -> String {
    bytes.iter().take(4).map(|b| format!("{b:02x}")).collect()
}

/// Every verifying key embedded at compile time (supports multiple keys / rotation).
pub fn embedded_verifying_keys() -> Vec<EmbeddedVerifyingKeyInfo> {
    PUBLIC_KEY_RING
        .iter()
        .map(|entry| EmbeddedVerifyingKeyInfo {
            kid: entry.kid.to_string(),
            fingerprint: verifying_key_fingerprint(entry.bytes),
        })
        .collect()
}

/// Key ids (`kid`) of Ed25519 verifying keys embedded in this binary at compile time.
pub fn embedded_verifying_key_ids() -> Vec<&'static str> {
    PUBLIC_KEY_RING.iter().map(|k| k.kid).collect()
}

/// Comma-separated embedded key ids for one-line CLI output (`super doctor`, etc.).
pub fn format_keyring_summary(kids: &[impl AsRef<str>]) -> String {
    if kids.is_empty() {
        return "none".into();
    }
    const MAX_INLINE: usize = 4;
    if kids.len() <= MAX_INLINE {
        return kids
            .iter()
            .map(AsRef::as_ref)
            .collect::<Vec<_>>()
            .join(", ");
    }
    let head = kids
        .iter()
        .take(3)
        .map(AsRef::as_ref)
        .collect::<Vec<_>>()
        .join(", ");
    format!("{head} (+{} more)", kids.len() - 3)
}

/// Comma-separated embedded key ids for one-line CLI output (`super doctor`, etc.).
pub fn embedded_keyring_summary() -> String {
    format_keyring_summary(
        &embedded_verifying_keys()
            .iter()
            .map(|k| k.kid.as_str())
            .collect::<Vec<_>>(),
    )
}

#[derive(Debug, Serialize, Deserialize)]
struct LicenseContainer {
    claims: LicenseClaims,
    signature: Vec<u8>,
}

/// Subscription expiry derived from signed claims and local clock.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum LicenseExpiryStatus {
    Active,
    Expired,
    Perpetual,
}

impl From<&LicenseClaims> for LicenseInfo {
    fn from(claims: &LicenseClaims) -> Self {
        let subscription_status = match license_expiry_status(claims) {
            Ok(LicenseExpiryStatus::Perpetual) => "perpetual",
            Ok(LicenseExpiryStatus::Active) => "active",
            Ok(LicenseExpiryStatus::Expired) => "expired",
            Err(_) => "unknown",
        };
        let max_superd_version = license_max_superd_version(claims);
        Self {
            issued_to: claims.issued_to.clone(),
            issued_at: claims.issued_at,
            major_version: claims.major_version,
            minor_version: claims.minor_version,
            issued_super_version: claims.issued_super_version.clone(),
            grants: claims.grants.clone(),
            expires_at: claims.expires_at,
            license_id: claims.license_id.clone(),
            features: Vec::new(),
            plugin_versions: HashMap::new(),
            subscription_status: subscription_status.to_string(),
            issued_for_version: license_issued_for_version(claims),
            max_superd_version: max_superd_version.clone(),
            supported_super_version: max_superd_version,
            superd_version: None,
            version_in_range: None,
            upgrade_url: LICENSE_UPGRADE_URL.to_string(),
            max_super_minor: licensed_max_super_minor(claims),
        }
    }
}

/// Product version recorded at issuance (e.g. `1.2.0`).
pub fn license_issued_for_version(claims: &LicenseClaims) -> Option<String> {
    if let Some(ref ver) = claims.issued_super_version {
        return Some(ver.clone());
    }
    claims
        .minor_version
        .map(|minor| format!("{}.{}.0", claims.major_version, minor))
}

/// Highest superd release this key permanently authorizes (derived from signed claims).
pub fn license_max_superd_version(claims: &LicenseClaims) -> String {
    match licensed_max_super_minor(claims) {
        Some(max_minor) => format!("{}.{}.x", claims.major_version, max_minor),
        None => format!("{}.x", claims.major_version),
    }
}

pub fn superd_within_license(claims: &LicenseClaims, superd_version: &str) -> bool {
    check_superd_version(claims, superd_version).is_ok()
}

fn current_unix_secs() -> anyhow::Result<u64> {
    Ok(SystemTime::now().duration_since(UNIX_EPOCH)?.as_secs())
}

fn ensure_not_expired(claims: &LicenseClaims) -> anyhow::Result<()> {
    if matches!(license_expiry_status(claims)?, LicenseExpiryStatus::Expired)
        && let Some(expires_at) = claims.expires_at
    {
        let now = current_unix_secs()?;
        anyhow::bail!("License expired at {expires_at} (current time {now})");
    }
    Ok(())
}

pub fn license_expiry_status(claims: &LicenseClaims) -> anyhow::Result<LicenseExpiryStatus> {
    match claims.expires_at {
        None => Ok(LicenseExpiryStatus::Perpetual),
        Some(expires_at) => {
            let now = current_unix_secs()?;
            if now > expires_at {
                Ok(LicenseExpiryStatus::Expired)
            } else {
                Ok(LicenseExpiryStatus::Active)
            }
        }
    }
}

fn decode_license_container(license_str: &str) -> anyhow::Result<LicenseContainer> {
    let trimmed = license_str.trim();
    if trimmed.len() > crate::security::MAX_LICENSE_B64_LEN {
        anyhow::bail!("License key too large");
    }

    let json_bytes = BASE64
        .decode(trimmed)
        .context("Invalid license format (Base64 decode failed)")?;

    if json_bytes.len() > crate::security::MAX_LICENSE_JSON_LEN {
        anyhow::bail!("License payload too large");
    }

    serde_json::from_slice(&json_bytes).context("Invalid license structure")
}

fn verifying_key_from_bytes(bytes: &[u8]) -> anyhow::Result<VerifyingKey> {
    let key_array: [u8; 32] = bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("Internal error: embedded public key has incorrect size"))?;
    VerifyingKey::from_bytes(&key_array)
        .map_err(|_| anyhow::anyhow!("Internal error: invalid embedded public key"))
}

fn unknown_kid_message(kid: &str) -> String {
    let known: Vec<&str> = PUBLIC_KEY_RING.iter().map(|k| k.kid).collect();
    format!(
        "This license was signed with key id '{kid}', which this superd build does not recognize \
         (embedded keys: {}). \
         Keep your current license file on this superd, or upgrade superd to a release that \
         includes that verifying key, then use this license. \
         {}",
        known.join(", "),
        license_help_footer()
    )
}

fn verify_container_with_key(
    container: &LicenseContainer,
    verifying_key: &VerifyingKey,
) -> anyhow::Result<()> {
    let signature = Signature::from_slice(&container.signature)
        .map_err(|_| anyhow::anyhow!("Invalid signature format"))?;
    let claims_bytes = serde_json::to_vec(&container.claims)?;
    verifying_key
        .verify(&claims_bytes, &signature)
        .map_err(|_| anyhow::anyhow!("signature mismatch"))?;
    Ok(())
}

fn verify_signature(license_str: &str) -> anyhow::Result<LicenseClaims> {
    let container = decode_license_container(license_str)?;

    let kid = container
        .claims
        .kid
        .as_deref()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        .ok_or_else(|| {
            anyhow::anyhow!(
                "License is missing signing key id (kid). Re-issue from your vendor — \
                 every license must include kid (e.g. k_a1b2c3d4)."
            )
        })?;

    let Some(entry) = PUBLIC_KEY_RING.iter().find(|k| k.kid == kid) else {
        anyhow::bail!("{}", unknown_kid_message(kid));
    };
    let verifying_key = verifying_key_from_bytes(entry.bytes)?;
    verify_container_with_key(&container, &verifying_key).map_err(|_| {
        anyhow::anyhow!(
            "License signature verification failed for key id '{kid}' (invalid or tampered)"
        )
    })?;
    crate::security::validate_license_grant_ids(&container.claims.grants)?;
    Ok(container.claims)
}

/// Verify against an explicit key (tests / tooling).
pub fn verify_license_with_key(
    license_str: &str,
    verifying_key: &VerifyingKey,
) -> anyhow::Result<LicenseClaims> {
    let container = decode_license_container(license_str)?;
    verify_container_with_key(&container, verifying_key).map_err(|_| {
        anyhow::anyhow!("License signature verification failed (invalid or tampered)")
    })?;
    crate::security::validate_license_grant_ids(&container.claims.grants)?;
    ensure_not_expired(&container.claims)?;
    Ok(container.claims)
}

/// Verify a Base64-encoded signed license string (strict: rejects expired keys).
pub fn verify_license(license_str: &str) -> anyhow::Result<LicenseClaims> {
    let claims = verify_signature(license_str)?;
    ensure_not_expired(&claims)?;
    Ok(claims)
}

/// Verify signature for superd runtime (honours signed `retain_grants_after_expiry` when set).
pub fn verify_license_for_superd(
    license_str: &str,
) -> anyhow::Result<(LicenseClaims, LicenseExpiryStatus)> {
    let claims = verify_signature(license_str)?;
    let expiry = license_expiry_status(&claims)?;
    if matches!(expiry, LicenseExpiryStatus::Expired)
        && claims.retain_grants_after_expiry == Some(false)
    {
        ensure_not_expired(&claims)?;
    }
    Ok((claims, expiry))
}

#[allow(dead_code)] // used by unit tests below
fn verify_license_for_superd_with_key(
    license_str: &str,
    verifying_key: &VerifyingKey,
) -> anyhow::Result<(LicenseClaims, LicenseExpiryStatus)> {
    let container = decode_license_container(license_str)?;
    verify_container_with_key(&container, verifying_key).map_err(|_| {
        anyhow::anyhow!("License signature verification failed (invalid or tampered)")
    })?;
    crate::security::validate_license_grant_ids(&container.claims.grants)?;
    let claims = container.claims;
    let expiry = license_expiry_status(&claims)?;
    if matches!(expiry, LicenseExpiryStatus::Expired)
        && claims.retain_grants_after_expiry == Some(false)
    {
        ensure_not_expired(&claims)?;
    }
    Ok((claims, expiry))
}

/// Parse the major version from a semver-like string (e.g. "1.1.9" -> 1).
pub fn parse_major_version(version: &str) -> u32 {
    parse_semver(version)
        .map(|(major, _, _)| major)
        .unwrap_or(0)
}

/// Parse `major.minor.patch` from a semver-like string (missing parts default to 0).
pub fn parse_semver(version: &str) -> Option<(u32, u32, u32)> {
    let mut parts = version.split('.');
    let major = parts.next()?.parse().ok()?;
    let minor = parts.next().and_then(|s| s.parse().ok()).unwrap_or(0);
    let patch = parts.next().and_then(|s| s.parse().ok()).unwrap_or(0);
    Some((major, minor, patch))
}

/// Minor line used for version cap checks (explicit `minor_version`, else parsed from `issued_super_version`).
pub fn licensed_minor_line(claims: &LicenseClaims) -> Option<u32> {
    if let Some(minor) = claims.minor_version {
        return Some(minor);
    }
    claims
        .issued_super_version
        .as_deref()
        .and_then(parse_semver)
        .map(|(_, minor, _)| minor)
}

/// Highest allowed semver minor within `major_version` (explicit claim or legacy `minor_ahead` delta).
pub fn licensed_max_super_minor(claims: &LicenseClaims) -> Option<u32> {
    if let Some(max_minor) = claims.max_super_minor {
        return Some(max_minor);
    }
    match (licensed_minor_line(claims), claims.minor_ahead) {
        (Some(issue_minor), Some(ahead)) => Some(issue_minor.saturating_add(ahead)),
        _ => None,
    }
}

/// Human-readable maximum licensed superd version for logs and CLI.
pub fn licensed_version_scope(claims: &LicenseClaims) -> String {
    if let Some(issued) = license_issued_for_version(claims) {
        format!("{issued} → max {}", license_max_superd_version(claims))
    } else {
        license_max_superd_version(claims)
    }
}

/// Check whether `superd` semver is within the signed major/minor policy.
pub fn check_superd_version(claims: &LicenseClaims, superd_version: &str) -> Result<(), String> {
    // Multi-product keys: superd only accepts Super Pro (or legacy keys without product_id).
    if let Some(pid) = claims.product_id.as_deref() {
        let pid = pid.trim();
        if !pid.is_empty() && pid != "super-pro" {
            return Err(format!(
                "This license is for product '{pid}', not Super Pro. {}",
                license_help_footer()
            ));
        }
    }

    let (host_major, host_minor, _) = parse_semver(superd_version)
        .ok_or_else(|| format!("Invalid superd version '{superd_version}'"))?;

    if host_major != claims.major_version {
        return Err(format!(
            "This license is for Super {}.x (max {}). \
             You are running superd {superd_version}. {}",
            claims.major_version,
            license_max_superd_version(claims),
            license_help_footer()
        ));
    }

    let Some(max_minor) = licensed_max_super_minor(claims) else {
        return Ok(());
    };

    if host_minor > max_minor {
        return Err(format!(
            "This license supports superd up to {host_major}.{max_minor}.x. \
             You are running superd {host_major}.{host_minor}. {}",
            license_help_footer()
        ));
    }

    Ok(())
}

#[cfg(test)]
mod semver_tests {
    use super::*;
    use crate::license::claims::LicenseClaims;

    #[test]
    fn version_labels_are_explicit() {
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "t".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: Some(2),
            max_super_minor: Some(4),
            minor_ahead: None,
            issued_super_version: Some("1.2.0".into()),
            grants: vec![],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        assert_eq!(
            license_issued_for_version(&claims).as_deref(),
            Some("1.2.0")
        );
        assert_eq!(license_max_superd_version(&claims), "1.4.x");
        assert!(superd_within_license(&claims, "1.2.0"));
        assert!(superd_within_license(&claims, "1.4.9"));
        assert!(!superd_within_license(&claims, "1.5.0"));
        assert!(!superd_within_license(&claims, "2.0.0"));
    }

    #[test]
    fn parse_semver_works() {
        assert_eq!(parse_semver("1.2.0"), Some((1, 2, 0)));
        assert_eq!(parse_semver("2"), Some((2, 0, 0)));
    }

    #[test]
    fn issued_super_version_still_parses_minor_for_display() {
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "t".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: Some(4),
            minor_ahead: None,
            issued_super_version: Some("1.2.0".into()),
            grants: vec![],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        assert_eq!(licensed_minor_line(&claims), Some(2));
        assert!(check_superd_version(&claims, "1.4.0").is_ok());
        assert!(check_superd_version(&claims, "1.5.0").is_err());
    }

    #[test]
    fn max_super_minor_caps_upper_bound_only() {
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "t".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: Some(2),
            max_super_minor: Some(4),
            minor_ahead: None,
            issued_super_version: Some("1.2.0".into()),
            grants: vec![],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        assert!(check_superd_version(&claims, "1.0.0").is_ok());
        assert!(check_superd_version(&claims, "1.4.0").is_ok());
        assert!(check_superd_version(&claims, "1.5.0").is_err());
        assert!(check_superd_version(&claims, "2.0.0").is_err());
    }

    #[test]
    fn legacy_minor_ahead_delta_still_works() {
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "t".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: Some(2),
            max_super_minor: None,
            minor_ahead: Some(2),
            issued_super_version: Some("1.2.0".into()),
            grants: vec![],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        assert_eq!(licensed_max_super_minor(&claims), Some(4));
        assert_eq!(license_max_superd_version(&claims), "1.4.x");
        assert!(check_superd_version(&claims, "1.4.9").is_ok());
        assert!(check_superd_version(&claims, "1.5.0").is_err());
    }

    #[test]
    fn legacy_license_major_only() {
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "t".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec![],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        assert_eq!(license_max_superd_version(&claims), "1.x");
        assert!(check_superd_version(&claims, "1.9.0").is_ok());
        assert!(check_superd_version(&claims, "2.0.0").is_err());
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::license::claims::LicenseClaims;
    use ed25519_dalek::{Signer, SigningKey};
    use rand::rngs::OsRng;

    fn sign_claims(signing_key: &SigningKey, claims: &LicenseClaims) -> String {
        let claims_bytes = serde_json::to_vec(claims).unwrap();
        let signature = signing_key.sign(&claims_bytes);
        let container = LicenseContainer {
            claims: claims.clone(),
            signature: signature.to_bytes().to_vec(),
        };
        BASE64.encode(serde_json::to_vec(&container).unwrap())
    }

    #[test]
    fn parse_major_version_works() {
        assert_eq!(parse_major_version("1.1.9"), 1);
        assert_eq!(parse_major_version("2.0.0"), 2);
    }

    #[test]
    fn expired_license_still_loads_for_superd() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "expired@example.com".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec!["security".into()],
            expires_at: Some(2),
            retain_grants_after_expiry: Some(true),
            license_id: Some("lic-test".into()),
        };
        let token = sign_claims(&signing_key, &claims);
        let verifying_key = signing_key.verifying_key();
        let (verified, status) = verify_license_for_superd_with_key(&token, &verifying_key)
            .expect("superd accepts expired");
        assert_eq!(status, LicenseExpiryStatus::Expired);
        assert_eq!(verified.issued_to, "expired@example.com");
    }

    #[test]
    fn rejects_expired_license() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let verifying_key = signing_key.verifying_key();
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "expired@example.com".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec!["security".into()],
            expires_at: Some(2),
            retain_grants_after_expiry: Some(true),
            license_id: Some("lic-test".into()),
        };
        let token = sign_claims(&signing_key, &claims);
        assert!(verify_license_with_key(&token, &verifying_key).is_err());
    }

    #[test]
    fn verify_signature_requires_kid() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let claims = LicenseClaims {
            product_id: Some("super-pro".into()),
            kid: None,
            issued_to: "t@example.com".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec!["security".into()],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        let token = sign_claims(&signing_key, &claims);
        let err = verify_license(&token).unwrap_err().to_string();
        assert!(err.contains("kid"), "{err}");
    }

    #[test]
    fn claims_without_kid_still_verify_with_explicit_key() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let verifying_key = signing_key.verifying_key();
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "legacy".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec!["security".into()],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: None,
        };
        let token = sign_claims(&signing_key, &claims);
        verify_license_with_key(&token, &verifying_key).expect("legacy license should verify");
    }

    #[test]
    fn superd_rejects_expired_when_claim_says_so() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let claims = LicenseClaims {
            product_id: None,
            kid: None,
            issued_to: "expired@example.com".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec!["security".into()],
            expires_at: Some(2),
            retain_grants_after_expiry: Some(false),
            license_id: Some("lic-hard".into()),
        };
        let token = sign_claims(&signing_key, &claims);
        let verifying_key = signing_key.verifying_key();
        assert!(verify_license_for_superd_with_key(&token, &verifying_key).is_err());
    }

    #[test]
    fn unknown_kid_suggests_upgrade_or_keep_license() {
        let signing_key = SigningKey::generate(&mut OsRng);
        let claims = LicenseClaims {
            product_id: Some("super-pro".into()),
            kid: Some("future-k".into()),
            issued_to: "newkey@example.com".into(),
            issued_at: 1,
            major_version: 1,
            minor_version: None,
            max_super_minor: None,
            minor_ahead: None,
            issued_super_version: None,
            grants: vec!["security".into()],
            expires_at: None,
            retain_grants_after_expiry: None,
            license_id: Some("lic-new".into()),
        };
        let token = sign_claims(&signing_key, &claims);
        let err = verify_license(&token).unwrap_err().to_string();
        assert!(err.contains("future-k"), "{err}");
        assert!(
            err.contains("Keep your current license") || err.contains("upgrade superd"),
            "{err}"
        );
    }

    #[test]
    fn embedded_keyring_matches_public_key_ring() {
        let keys = embedded_verifying_keys();
        assert_eq!(keys.len(), PUBLIC_KEY_RING.len());
        for (info, entry) in keys.iter().zip(PUBLIC_KEY_RING.iter()) {
            assert_eq!(info.kid, entry.kid);
            assert_eq!(info.fingerprint.len(), 8);
        }
        assert!(!embedded_keyring_summary().is_empty());
    }

    #[test]
    fn keyring_summary_truncates_many_keys() {
        let kids = ["a", "b", "c", "d", "e"];
        assert_eq!(format_keyring_summary(&kids), "a, b, c (+2 more)");
        assert_eq!(format_keyring_summary(&["only"]), "only");
        assert_eq!(format_keyring_summary(&[] as &[&str]), "none");
    }
}
